[sel ORDER_SEL top]
[s]Regroup[e]
[s]Split up[e]
[s]Priority: explore[e]
[s]Priority: defeat Shadows[e]
[s]Request a specific BGM[e]
[s]Ask Fuuka for something[e]
[s]Change party[e]
[s]Use the clock[e]
[s]Mod Menu[e]
[s]Cancel[e]
[s]Debug[e]

[sel HUKA_OREDER_SEL top]
[s]Ask for an Escape Route[e]
[s]Ask for a specific BGM[e]
[s]Change party[e]
[s]Use the clock[e]
[s]Mod Menu[e]
[s]Cancel the request[e]
[s]Debug[e]

[msg CALL_CLOCK_TRAESTO]
[s]> Use 1 [f 2 5 3 13 0] to use the Clock?
[n](You have [f 2 4 1] currently.)[w][e]

[msg NO_TRAESTO]
[s]> No [f 2 5 3 13 0] available
[n]to use the Clock![w][e]