[sel SAVE_OR_HEAL top]
[s]Save[e]
[s]Heal party[e]
[s]Heal all[e]
[s]Check battle tips[e]
[s]Cancel[e]

[sel HEAL_OK top]
[s]Heal[e]
[s]Cancel[e]

[msg WHAT_DO_YOU_WANT]
[s]> What would you like to do?
[n][w][e]

[msg HEAL_DONE]
[s]> All members' HP and SP recovered!
[n][w][e]

[msg HEAL_DONE_PT]
[s]> The party's HP and SP has
[n]been recovered!
[n][w][e]

[msg HEAL_REQUIRE]
[s]> Healing will cost [clr 1][f 2 4 0] yen[clr 0].
[n]Heal? (Carrying: [clr 1][f 2 4 1] yen[clr 0])
[n][w][e]

[msg HEAL_NOMONEY]
[s]> You don't have enough money...
[n][w][e]

[msg HEAL_NOMORE]
[s]> You don't need to heal right now.
[n][w][e]

[msg SYS_TUTORIAL_FIRST]
[s]> Refreshers on battle are listed here.
[n]The available topics are...
[n][w][e]

[sel SYS_TUTORIAL_SEL top]
[s]Battle tips[e]
[s]Exploration tips[e]
[s]Gaining strength[e]
[s]Things to look out for[e]
[s]Cancel[e]

[msg SYS_TUTORIAL_01]
[s]If you strike the enemy's weakness,
[n]or get a critical hit, you will knock
[n]them down.
[n] 
[n]When this happens, you get a 1 More
[n]chance, and can act again.
[n][w][e]
[s]You may perform a follow-up attack on
[n]the same enemy or attack another foe.
[n] 
[n]If an enemy is knocked down and you
[n]knock down a different enemy, you will
[n]be able to act yet again.
[n][w][e]
[s]In this way, you may attack as long as
[n]you continue knocking enemies down.
[n] 
[n]If you attack a Downed enemy's weak
[n]point, they will become dizzy and lose
[n]a turn.
[n][w][e]
[s]It is thus important to Analyze your
[n]enemy's weaknesses to gain an advantage.
[n] 
[n]You can Analyze by asking your operator
[n]in the Tactics menu or by pressing the
[n]Analyze button.
[n][w][e]
[s]If you knock down all the enemies,
[n]you may have the whole party perform
[n]an All-Out Attack. 
[n]These are powerful, unavoidable, and
[n]extremely effective.
[n][w][e]

[msg SYS_TUTORIAL_02]
[s]If you press the Sub Menu button while in
[n]Tartarus, you may order your party
[n]members to split up. While they are
[n]split up, they will find stairs and
[n]escape points, and retrieve items from
[n]treasure chests.
[n][w][e]
[s]If a party member encounters a Shadow
[n]while split up, they will enter battle.
[n]Party members tied up in battle cannot
[n]use field skills or change their
[n]equipment from the menu.
[n][w][e]
[s]You cannot use skills or items on party
[n]members who are too far away.
[n]Distant party members will have darkened
[n]portraits in the bottom right of the
[n]screen, so pay attention.
[n][w][e]

[msg SYS_TUTORIAL_03]
[s]It is important to level up yourself
[n]to raise your HP and SP, and to level
[n]up your Personas to make them stronger.
[n] 
[n] 
[n] 
[n][w][e]
[s]The Persona equipped at the end of a
[n]victorious battle will gain experience
[n]and potentially level up.
[n] 
[n] 
[n] 
[n][w][e]
[s]When a Persona levels up, not only do its
[n]stats increase, it will sometimes learn
[n]new skills.
[n] 
[n]To be effective in battle, it will need
[n]to have a strong skill set.
[n][w][e]
[s]Personas which have already acquired all
[n]of their skills, or Personas that are
[n]not as strong as you'd like, can be
[n]fused at the Velvet Room. Through fusion,
[n]you can create new Personas.
[n] 
[n][w][e]
[s]If you have a Social Link matching the
[n]new Persona's arcana, the new Persona
[n]will gain bonus experience and rise to
[n]a higher level than predicted.
[n] 
[n] 
[n][w][e]
[s]Raising your Social Links as high as
[n]you can before fusion will allow you
[n]to fuse Personas at their strongest.
[n] 
[n] 
[n] 
[n][w][e]

[msg SYS_TUTORIAL_04]
[s]Be careful of occasions when the
[n]layout of Tartarus changes, and of
[n]your friends' health.
[n] 
[n] 
[n] 
[n][w][e]
[s]When the layout changes, there is a
[n]high likelihood of finding more
[n]treasure chests, rare Shadows, and
[n]other unusual effects. These effects
[n]will disappear once you ascend to
[n]a new floor.
[n][w][e]
[s]The various states of health are Good,
[n]Great, Tired, and Sick.
[n][w][e]
[s]"Great" will enhance your effectiveness
[n]in battle, making it the best time to
[n]fight in Tartarus.
[n]However, "Tired" and "Sick" will make
[n]you weak and put you at a disadvantage.
[n][w][e]
[s]If you fight too much in Tartarus, you
[n]will be Tired the next day. Staying
[n]Tired may sometimes cause your
[n]condition to worsen into Sick.
[n] 
[n] 
[n][w][e]
[s]At these times, be sure to cut your
[n]exploration short or do something to
[n]alleviate the exhaustion.
[n] 
[n]Make sure that you are at your best
[n]during important battles.
[n][w][e]
