[msg ItemPrompt_F [Fuuka]]
[s]What floor would you like to[n]warp to?[w][e]

[msg ItemPrompt_M [Mitsuru]]
[s]What floor would you like to[n]warp to?[w][e]

[msg FloorConfirm_F [Fuuka]]
[s]You'd like to warp to floor [f 2 4 0],[n]correct?[n][w][e]

[msg FloorConfirm_M [Mitsuru]]
[s]You'd like to warp to floor [f 2 4 0]?[n][w][e]

[sel ESCAPE_SEL top]
[s]"Yes, please."[e]
[s]"Never mind."[e]

[sel ESCAPE_SEL_G top]
[s]"Yes, please!"[e]
[s]"That's okay."[e]

[msg WarpConfirm_F [Fuuka]]
[s]Alright, just sit tight. Beginning[n]warp now![n][w][e]

[msg WarpConfirm_M [Mitsuru]]
[s]Confirming warp, please stay where[n]you are.[w][e]

[msg TooHigh_F [Fuuka]]
[s]I'm sorry but it appears that you've[n]never climbed that high.
[n]You'll need to find another way up.
[n][w][e]

[msg TooHigh_M [Mitsuru]]
[s]It appears you've never reached that floor.
[n]You'll need to reach that floor before I allow
[n]you to warp there.
[n][w][e]

[msg AnythingElse_F [Fuuka]]
[s]Alright. Do you need anything else?[n][w][e]

[msg AnythingElse_M [Mitsuru]]
[s]Do you need anything else, leader?[n][w][e]

[sel YesOrNo top]
[s]Yes[e]
[s]No[e]
