[msg HUKA_ORDER_ESCAPE [Fuuka]]
[s]Okay. But, are you sure you want to[n]go back?[n][w][e]

[msg FUUKA_ESCAPE_TRAESTO [Fuuka]]
[s]Okay. But, are you sure you want to[n]use a [f 2 5 3 13 0]?[n][w][e]

[msg MITSURU_ORDER_ESCAPE [Mitsuru]]
[s]Are you sure you'd like to return to[n]the entrance?[n][w][e]

[msg MITSURU_ESCAPE_TRAESTO [Mitsuru]]
[s]Do you want to use a [f 2 5 3 13 0] to go[n]back?[n][w][e]

[msg HUKA_ORDER_ESCAPE_GO [Fuuka]]
[s]Got it! Just stay there.[n][w][e]

[msg FUUKA_GO_TRAESTO [Fuuka]]
[s]Got it![n][w][e]

[msg MITSURU_GO_TRAESTO [Mitsuru]]
[s]Understood.[n][w][e]

[sel ESCAPE_SEL top]
[s]"Yes, please."[e]
[s]"Never mind."[e]

[sel ESCAPE_SEL_G top]
[s]"Yes, please!"[e]
[s]"That's okay."[e]

[msg HUKA_ORDER_RESTART [Fuuka]]
[s]...Is there anything else?[n][w][e]

[msg MITSURU_ORDER_RESTART [Mitsuru]]
[s]Is there something else you need?[n][w][e]

[msg FUUKA_NO_TRAESTO [Fuuka]]
[s]Um... you don't seem to have a[n][f 2 5 3 13 0]... You'll have to[n]find another way back...[n][w][e]

[msg MITSURU_NO_TRAESTO [Mitsuru]]
[s]You don't have a [f 2 5 3 13 0],[n]Leader. You'll need to find a different[n]way out.[n][w][e]