
[sel SCHOOL_SHOTCUTSEL top]
[s]1F, Main Lobby[e]
[s]1F, Faculty Office Hallway[e]
[s]1F, Laboratory Hallway[e]
[s]1F, Corridor[e]
[s]1F, Gym Hallway[e]
[s]2F, Classroom Hallway[e]
[s]Classroom[e]
[s]Rooftop[e]
[s]Entranceway[e]
[s]Next Page[e]
[s]Previous Page[e]
[s]Elsewhere[e]
[s]Cancel[e]

[sel DORMITORY_SHOTCUTSEL top]
[s]1F, Lounge[e]
[s]2F, Hallway[e]
[s]3F, Hallway[e]
[s]4F, Hallway[e]
[s]Command Room[e]
[s]Your Room[e]
[s]Bed[e]
[s]Elsewhere[e]
[s]Cancel[e]

[sel MAP_SHOTCUTSEL top]
[s]Gekkoukan High[e]
[s]Dorm[e]
[s]Paulownia Mall[e]
[s]Strip Mall[e]
[s]Port Island Station[e]
[s]Shrine[e]
[s]Cancel[e]

[msg QuickTravelPlus_Text]
[s]Where to?[e]

[sel MALL_SHORTCUTT top]
[s]Tatsumi East Police Station[e]
[s]Blue Beard Pharmacy[e]
[s]Antique Shop[e]
[s]Club Escapade[e]
[s]Velvet Room[e]
[s]Elsewhere[e]
[s]Cancel[e]

[sel TARTAROS_SHORTCUT top]
[s]Tartarus[e]
[s]Velvet Room[e]
[s]Teleporter[e]
[s]Monad[e]
[s]Outside[e]
[s]Cancel[e]

[sel KYOTO_SHOTCUTSEL top]
[s]1F Lobby[e]
[s]2F Hallway[e]
[s]3F Hallway[e]
[s]Cancel[e]

[sel TEMPLE_SHOTCUTSEL top]
[s]Town Map[e]
[s]Cancel[e]

[sel STATION_SHOTCUTSEL top]
[s]Station Outskirts[e]
[s]Tatsumi Port Island Station[e]
[s]Town Map[e]
[s]Cancel[e]

[sel SHOP_SHOTCUTSEL top]
[s]Iwatodai Station[e]
[s]Strip Mall, 2F[e]
[s]Town Map[e]
[s]Cancel[e]






