[msg ModMenuName]
[s]Amicitia Mod Menu[w][e]

[msg AboutMsg[About this menu]]
[s]Created by [clr 1]DniweTamp[clr 0] using TGE's[n][clr 9]AtlusScriptCompiler[clr 0] tool.[w][e]

[sel ModMenu]
[s]Use original square function[e]
[s]Player[e]
[s]Battle Select[e]
[s]Sound Test[e]
[s]Field Select[e]
[s]Next Page[e]

[sel ModMenu2]
[s]Event Select[e]
[s]Facility[e]
[s]Flags[e]
[s]Font Test[e]
[s]About[e]
[s]Set up favorites[e]
[s]Previous Page[e]

[sel PlayerMenu]
[s]Evolve party member persona[e]
[s]Social Stats[e]
[s]Items[e]
[s]Party Edit[e]
[s]Count Edit[e]
[s]Next Page[e]

[sel BattleSelect]
[s]Manual Input[e]
[s]Tartarus Guardian Select[e]
[s]Boss Select[e]

[msg TAR_SEL1_Text]
[s]Block Select[e]

[msg TAR_SEL2_Text]
[s]Battle Select[e]

[sel BlockSelect]
[s]Block 1[e]
[s]Block 2[e]
[s]Block 3[e]
[s]Block 4[e]
[s]Block 5[e]
[s]Block 6[e]

[sel TarTarSelect_1]
[s]Venus Eagle[e]
[s]Dancing Hand[e]
[s]Rampage Drive[e]

[sel TarTarSelect_2]
[s]Crying Table[e]
[s]Change Relic[e]
[s]Golden Beetles[e]
[s]Intrepid Knight[e]
[s]Furious Gigas[e]

[sel TarTarSelect_3]
[s]Fanatic Tower[e]
[s]Magical Magus[e]
[s]Neutral Dancer[e]

[sel TarTarSelect_4]
[s]Arcane Turrets[e]
[s]Sleeping Table[e]
[s]Hell Knights[e]
[s]Mythical Gigas[e]

[sel TarTarSelect_5]
[s]Judgement Swords[e]
[s]Stasis Giant[e]
[s]Phantom King[e]
[s]Royal Dancers[e]
[s]Reckoning Dice[e]

[sel TarTarSelect_6]
[s]Noble Seeker[e]
[s]Carnal Snakes[e]
[s]World Balance[e]
[s]Fierce Cyclops[e]
[s]Jotun of Grief[e]


[msg BOSS_SEL1_Text]
[s]Boss Select (Page 1/3)[e]

[msg BOSS_SEL2_Text]
[s]Boss Select (Page 2/3)[e]

[msg BOSS_SEL3_Text]
[s]Boss Select (Page 3/3)[e]

[sel BossSelect_1]
[s]Priestess[e]
[s]Emperor/Empress[e]
[s]Hierophant[e]
[s]Lovers[e]
[s]Chariot/Justice[e]
[s]Hermit[e]
[s]Next Page[e]

[sel BossSelect_2]
[s]Fortune/Strength[e]
[s]Takaya/Jin[e]
[s]Hanged Man[e]
[s]Chidori[e]
[s]Next Page[e]
[s]Previous Page[e]

[sel BossSelect_3]
[s]Jin[e]
[s]Takaya[e]
[s]Nyx[e]
[s]Elizabeth[e]
[s]Theodore[e]
[s]Margaret[e]
[s]Previous Page[e]

[sel PlayerMenu2]
[s]Set Protagonist Name[e]
[s]Max Money[e]
[s]Time Travel[e]
[s]Previous Page[e]

[sel CountSelect]
[s]Enter Count[e]
[s]Edit Count Value[e]

[msg CountDlg [Count Select]]
[s]Choose the first 4 digits of[n]the count to load.[n][w][e]

[msg CountDlg2 [Count Edit]]
[s]Choose the last 4 digits of[n]the count to modify.[n]Current count value for [f 2 4 1] is [f 2 4 2][n][w][e]

[msg PersonaAddPrompt [Add Persona]]
[s]Input the ID of the Persona to add.[n](max. 3 digits)[w][e]

[msg SkillPrompt [Add Skill]]
[s]Enter the ID of the skill to add.[n](max. 3 digits)[w][e]

[sel StatsMenu]
[s]Academics[e]
[s]Charm[e]
[s]Courage[e]

[msg StatPrompt [Stats]]
[s]Add how many points?[n](max. 2 digits)[w][e]

[sel ItemMenu]
[s]Melee Weapons[e]
[s]Armor[e]
[s]Boots[e]
[s]Accessories[e]
[s]Items[e]
[s]Key Items[e]
[s]Skill Cards[e]

[msg ItemPrompt [Items]]
[s]Enter the item ID you want.[n](max. 4 digits)[w][e]

[msg ItemPrompt2 [Items]]
[s]Enter how many items you want.[n](max. 2 digits)[w][e]

[msg ItemAdded]
[s]Obtained [f 2 4 2] of [f 2 4 1].[w][e]

[msg CommuPrompt]
[s]Set the Social Link level[n]you want to have.[w][e]

[sel PartyEditMenu]
[s]Add Party Members[e]
[s]Remove Party Members[e]
[s]Set Tiredness[e]

[sel SetTiredness]
[s]Great[e]
[s]Good[e]
[s]Tired[e]

[msg MoneyAdded]
[s]You received [clr 1]99999999[clr 0] yen.[w][e]

[msg EncounterPrompt]
[s]Set the number of the encounter[n]you want to fight (max. 3 digits).[w][e]

[msg SelectBgmDialog]
[s]Select a bgm to play (max. 5 digits).[w][e]

[sel FieldSelect]
[s]Enter Field ID[e]
[s]Load Field[e]
[s]Load 3D Field[e]

[sel EventSelect]
[s]Enter Event ID[e]
[s]Load Event ID[e]

[msg FontTest[The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]abcdefghijklmnopqrstuvwxyz[n][w][e]
//[s]1234567890-_.:,;|!"#$%&/[n]()=?+*{}^\<>`~'@[w][e]

[msg FieldDlg [Field Select]]
[s]Choose the first 3 digits of[n]the field to load.[n]Current field: [f 2 4 1], [f 2 4 2].[n][w][e]

[msg FieldDlg2 [Field Select]]
[s]Choose the last 3 digits of[n]the field to load.[n]Current field: [f 2 4 1], [f 2 4 2].[n][w][e]

[msg EventDlg [Event Select]]
[s]Choose the first 3 digits of[n]the event to load.[n][w][e]

[msg EventDlg2 [Event Select]]
[s]Choose the last 3 digits of[n]the event to load.[n][w][e]

[msg PRINTVAR]
[s]> Current value for month is [f 2 4 0][n][w][e]
[s]> Current value for day is [f 2 4 1][n][w][e]


[sel TimeSelect]
[s]Enter Date[e]
[s]Load Date[e]

[msg TimeTravel [Time Travel]]
[s]Choose the first 2 digits of[n]the month to load.[n][w][e]

[msg TimeTravel2 [Time Travel]]
[s]Choose the last 2 digits of[n]the day to load.[n][w][e]

[msg CountEdit [Count Edit]]
[s]Choose the first 4 digits of[n]the count to load.[n][w][e]

[msg CountEdit2 [Count Edit]]
[s]Choose the last 4 digits of[n]the count value to modify.[n][w][e]

[sel FacilityMenu]
[s]Town map[e]
[s]Save Menu[e]
[s]Persona Fusion[e]

[sel FlagMenu]
[s]Manual Input[e]
[s]Add Party Members[e]
[s]Remove Party Members[e]
[s]Navigator[e]
[s]Mass Flag Editor[e]

[msg SelectFlagDialog]
[s]Select a flag to edit (max. 4 digits).[w][e]

[msg FlagCheckOn]
[s]Flag [f 2 4 1] is on.[w][e]

[msg FlagCheckOff]
[s]Flag [f 2 4 1] is off.[w][e]

[msg FlagOn]
[s]Flag [f 2 4 1] has been enabled.[w][e]

[msg FlagOff]
[s]Flag [f 2 4 1] has been disabled.[w][e]

[sel NaviMenu]
[s][f 2 4 6][e]
[s][f 2 4 4][e]
[s]None[e]

[sel FlagMassEditor]
[s]Disable all flags[e]
[s]Enable all flags[e]
[s]Complete all quests[e]
[s]Enable all Tartarus guardians[e]
[s]Enable all warps[e]
[s]Swap enabled/disabled flags[e]
[s]Toggle range of flags[e]

[msg FlagRangePrompt]
[s]Enter the start of the range to narrow down.[n](Max 4 digits, press Circle to end).[w][e]

[msg FlagRangePrompt2]
[s]Enter the end of the range to narrow down.[n](Max 4 digits, press Circle to end).[w][e]

[msg ColorTest]
[s]Colors: [clr 0]0 [clr 1]1 [clr 2]2 [clr 3]3 [clr 4]4 [clr 5]5 [clr 6]6 [clr 7]7 [clr 8]8 [clr 9]9[clr 10]10 [clr 11]11 [clr 12]12 [clr 13]13 [clr 14]14 [clr 15]15[n]
[clr 16]16 [clr 17]17 [clr 18]18 [clr 19]19 [clr 20]20 [clr 21]21 [clr 22]22 [clr 23]23 [clr 24]24 [clr 25]25 [clr 26]26 [clr 27]27 [clr 28]28 [clr 29]29 [clr 30]30 [clr 31]31[w][e]

[msg FavoritesName]
[s]Press L/R to see other pages[w][e]

[msg MSGVarTest]
[s]Variable: [f 2 4 1][w][e]

[msg LoadCheckError]
[s]Set the required parameters[n]before attempting to load![w][e]

[msg NotImplemented]
[s]This feature is currently not implemented.[n][w][e]

[msg UnstableFunc]
[s]This feature is unstable on real hardware.[n]Do you still wish to use it?[n][w][e]

[msg UnstableSC]
[s]This feature is unstable and only designed[n]for small testing. Do you still[n]wish to proceed?[n][w][e]

[sel YesNo]
[s]Yes[e]
[s]No[e]

[msg MSGDummy]
[s][w][e]
