[msg WHO_HANG_WITH]
[s]> Who would you like to hang out with?[w][e]

[msg SeeWho]
[s]Who do you want to see?[e]

[sel LIST_OF_PEOPLE top]
[s]Akinari (Rank [f 2 4 1][f 2 4 26])[e]
[s]Mitsuru (Rank [f 2 4 2][f 2 4 25])[e]
[s]Yuko (Rank [f 2 4 3][f 2 4 20])[e]
[s]Chihiro (Rank [f 2 4 4][f 2 4 28])[e]
[s]Bebe (Rank [f 2 4 5][f 2 4 0])[e]
[s]Fuuka (Rank [f 2 4 6][f 2 4 24])[e]
[s]Aigis (Rank [f 2 4 7][f 2 4 26])[e]
[s]Yukari (Rank [f 2 4 8][f 2 4 23])[e]
[s]Hidetoshi (Rank [f 2 4 9][f 2 4 21])[e]
[s]Old Couple (Rank [f 2 4 10][f 2 4 22])[e]
[s]Kazushi (Rank [f 2 4 11][f 2 4 29])[e]
[s]Maiko (Rank [f 2 4 12][f 2 4 31])[e]
[s]Kenji (Rank [f 2 4 13][f 2 4 20])[e]
[s]Mamoru (Rank [f 2 4 14][f 2 4 30])[e]
[s]Keisuke (Rank [f 2 4 15][f 2 4 24])[e]
[s]Maya (Rank [f 2 4 16][f 2 4 21])[e]
[s]Tanaka (Rank [f 2 4 17][f 2 4 23])[e]
[s]Mutatsu (Rank [f 2 4 18][f 2 4 22])[e]
[s]Nozomi (Rank [f 2 4 19][f 2 4 27])[e]
[s]Cancel.[e]

[sel LIST_OF_PEOPLE_F top]
[s]Junpei (Rank [f 2 4 1][f 2 4 24])[e]
[s]Hidetoshi (Rank [f 2 4 2][f 2 4 21])[e]
[s]Old Couple (Rank [f 2 4 3][f 2 4 22])[e]
[s]Yukari (Rank [f 2 4 4][f 2 4 23])[e]
[s]Fuuka (Rank [f 2 4 5][f 2 4 23])[e]
[s]Mitsuru (Rank [f 2 4 6][f 2 4 21])[e]
[s]Aigis (Rank [f 2 4 7][f 2 4 26])[e]
[s]Rio (Rank [f 2 4 9][f 2 4 25])[e]
[s]Koromaru (Rank [f 2 4 10][f 2 4 21])[e]
[s]Ryoji (Rank [f 2 4 11])[e]
[s]Ken (Rank [f 2 4 12][f 2 4 25])[e]
[s]Maiko (Rank [f 2 4 13][f 2 4 27])[e]
[s]Bebe (Rank [f 2 4 14][f 2 4 0])[e]
[s]Tanaka (Rank [f 2 4 15][f 2 4 23])[e]
[s]Mutatsu (Rank [f 2 4 16][f 2 4 22])[e]
[s]Akihiko (Rank [f 2 4 17][f 2 4 29])[e]
[s]Akinari (Rank [f 2 4 18][f 2 4 26])[e]
[s]Shinjiro (Rank [f 2 4 19][f 2 4 30])[e]
[s]Saori (Rank [f 2 4 20][f 2 4 25])[e]
[s]Cancel.[e]

[msg CURRENT_VALUE]
[s]> Current value for gVar76 is [f 2 4 25][n][w][e]

[msg NO_ONE]
[s]> No one is available right now.[n][w][e]

[msg JUN_NEARBY]
[s]> Junpei is nearby.[n][w][e]

[msg KAZ_NEARBY]
[s]> Kazushi is nearby.[n][w][e]

[msg YUK_NEARBY]
[s]> Yukari is nearby.[n][w][e]

[msg AIG_NEARBY]
[s]> Aigis is nearby.[n][w][e]

[msg KEN_NEARBY]
[s]> Kenji is nearby.[n][w][e]

[msg NARI_NEARBY]
[s]> Akinari is nearby.[n][w][e]

[msg MITS_NEARBY]
[s]> Mitsuru is nearby.[n][w][e]

[msg YUKO_NEARBY]
[s]> Yuko is nearby.[n][w][e]

[msg CHIH_NEARBY]
[s]> Chihiro is nearby.[n][w][e]

[msg BEBE_NEARBY]
[s]> Bebe is nearby.[n][w][e]

[msg FUCK_NEARBY]
[s]> Fuuka is nearby.[n][w][e]

[msg HIDE_NEARBY]
[s]> Hidetoshi is nearby.[n][w][e]

[msg BOOK_NEARBY]
[s]> The book store is nearby.[n][w][e]

[msg MAIK_NEARBY]
[s]> Maiko is nearby.[n][w][e]

[msg MAMO_NEARBY]
[s]> Mamoru is nearby.[n][w][e]

[msg KEIS_NEARBY]
[s]> Keisuke is nearby.[n][w][e]

[msg MAYA_NEARBY]
[s]> Maya is nearby.[n][w][e]

[msg TANA_NEARBY]
[s]> Tanaka is nearby.[n][w][e]

[msg MUTA_NEARBY]
[s]> Mutatsu is nearby.[n][w][e]

[msg NOZO_NEARBY]
[s]> Nozomi is nearby.[n][w][e]

[msg SAOR_NEARBY]
[s]> Saori is nearby.[n][w][e]

[msg RIO_NEARBY]
[s]> Rio is nearby.[n][w][e]

[msg KORO_NEARBY]
[s]> Koromaru is nearby.[n][w][e]

[msg RYOJ_NEARBY]
[s]> Ryoji is nearby.[n][w][e]

[msg KENCOOL_NEARBY]
[s]> Ken is nearby.[n][w][e]

[msg AKIH_NEARBY]
[s]> Akihiko is nearby.[n][w][e]

[msg GET_IN_THE_EVA_SHINJI]
[s]> Shinjiro is nearby.[n][w][e]

[msg CHANGED_MIND_CHIH [Chihiro]]
[s][bup 25 162 65535 2]Y-you changed your mind?[n]Th-That's great![n][w][e]
[s][f 1 5] [n]> Chihiro seems excited...[n][w][e]
