[msg SquareMenuConfig]
[s][clr 1]Custom Sub Menu Setup[clr 0]
[n]Please select the features you would like to use.
[n]The recommended options are enabled by default.
[n] 
[n] 
[n][w][e]
[s][clr 1]Custom Sub Menu Setup[clr 0]
[n]If you change your mind later, don't worry!
[n]These settings can be changed at any time
[n]during normal gameplay.
[n] 
[n][w][e]

[sel ToggleMenu]
[s]On[e]
[s]Off[e]
[s]Cancel[e]

[sel YesNo]
[s]Yes[e]
[s]No[e]

[msg SquareMenuOptions_Text]
[s]Options (1/2 Press Back to Exit)[f 1 1][e]

[msg SquareMenuOptions_Text_2]
[s]Options (2/2 Press Back to Exit)[f 1 1][e]

[sel SquareMenuOptions]
[s]Mod Menu: [f 2 4 0][e]
[s]Quick Travel Plus: [f 2 4 1][e]
[s]Mobile Calendar: [f 2 4 2][e]
[s]Dungeon Options: [f 2 4 3][e]
[s]Find A Friend: [f 2 4 4][e]
[s]Save Anywhere: [f 2 4 5][e]
[s]Save Everyday: [f 2 4 6][e]
[s]Remove Filler Events: [f 2 4 7][e]
[s]Remove Lunch Invites: [f 2 4 8][e]
[s]Next[e]
[s]Previous[e]

[msg OptionsWarning]
[s]Access the Options Menu again by pressing
[n]the [f 0 1 2]Command Menu button[f 0 1 0] from the top level
[n]of the Sub Menu.[f 1 1][e]

[msg ModMenuWarning]
[s]Mod Menu access is enabled. Please note that
[n]Mod Menu is designed as a tool to aide in mod
[n]development. It is not a cheating tool.[f 1 1][e]

[msg ModMenuWarning_2]
[s]If you choose to use it as a cheating tool and
[n]irreversibly mess up your game, you will not 
[n]receive any support. You have been warned.[f 1 1][e]

[msg ModMenu_About[Mod Menu (DniweTamp)]]
[s]A powerful tool for modders. Enables options for
[n]calling of fields and events, toggling of flags,
[n]stat editing and much more. Use with caution![e]

[msg QuickTravelPlus_About[Quick Travel Plus (Dexxtrip)]]
[s]A quality of life tweak inspired by Persona 5. Expands 
[n]the fast travel menus with more locations for 
[n]improved overworld traversal.[e]

[msg MobileCalendar_About[Mobile Calendar]]
[s]Allows you to view the calendar from anywhere via
[n]an additional sub menu option.[e]

[msg DungeonOptions_About[Dungeon Options (Dexxtrip)]]
[s]Configurable quality of life tweaks for dungeon
[n]exploration. Enable to view the available options.[e]

[msg FindAFriend_About[Find A Friend (Dexxtrip)]]
[s]A quality of life tweak to make keeping track of
[n]Social Links less cumbersome. Adds a sub menu option
[n]to fast travel to their location when available.[e]

[msg SaveAnywhere_About[Save Anywhere]]
[s]Save your game from anywhere, straight from the sub
[n]menu. Normally, you would only be able to save from
[n]designated areas marked by the S icon.[e]

[msg SaveEveryday_About[Save Everyday (Dexxtrip)]]
[s]When enabled, you will be prompted to save every night
[n]whenever continuing to the next day.[e]

[msg RemoveFillerEvents_About[Remove Filler Events (Dexxtrip)]]
[s]When enabled, various "filler" required events will
[n]be skipped. This includes the entire Kyoto trip
[n]and various other events[e]

[msg RemoveLunchtimeInvites_About[Remove Lunch Invites (Dexxtrip)]]
[s]When enabled, hallway lunchtime invites when a social
[n]link is ready to rank up will be skipped.
[n]Recommend enabling with Find a Friend.[e]

[msg DungeonOptions_Text]
[s]Dungeon Options[e]

[sel DungeonOptions]
[s]Show the Clock: [f 2 4 0][e]
[s]Auto Healing: [f 2 4 1][e]
[s]Show Organize Party: [f 2 4 2][e]
[s]Show Floor Select: [f 2 4 3][e]
[s]Use Traesto Gems: [f 2 4 4][e]
[s]Default Direct Commands: [f 2 4 5][e]
[s]Game Over Skip: [f 2 4 6][e]
[s]Done[e]

[msg ShowTheClock_About[Clock Option (moddaman)]]
[s]Allows you to purchase healing from the clock at the
[n]floor of Tartarus via an additional sub menu option.
[n]Normally you would need to return to the entrance.[e]

[msg AutoHealing_About[Auto Healing (Dexxtrip)]]
[s]When enabled, upon climbing a floor, you will
[n]automatically heal to the max using your SP. 
[n]Saving you the time of manually healing.[e]

[msg OrganizeParty_About[Organize Party (moddaman)]]
[s]A quality of life tweak that allows you to swap party
[n]members via a new sub menu option without
[n]needing to leave Tartarus.[e]

[msg FloorSelect_About[Floor Select (Dexxtrip)]]
[s]Allows you to instantly warp to a selected floor once 
[n]reached via a new sub menu option.[e]

[msg TraestoGems_About[Use Traesto Gems (Dexxtrip)]]
[s]Allows you to instantly use a Traesto gem from the
[n]sub menu for easier escaping of Tartarus.[e]

[msg DefaultDirectCommands_About[Default Direct Commands (Dexxtrip)]]
[s]Sets all party members tactics to direct
[n]commands by default.[e]

[msg GameOverSkip_About[Game Over Skip (Dexxtrip)]]
[s]Skips the velvet room cutscene upon dying and 
[n]instead allows you to instantly retry.[e]

[msg FindAFriendOptions_Text]
[s]Find A Friend Options[e]

[msg QuickTravelPlusOptions_Text]
[s]QT+ Options[e]

[sel QuickTravelPlusOptions]
[s]Go Back Home Easily: [f 2 4 0][e]
[s]Done[e]

[msg GBHE_TOGGLE[Go Back Home Easily (Dexxtrip)]]
[s]If "On", returning to the dorm on days off will
[n]not progress time forward.[e]

[sel FindAFriendOptions]
[s]Spoiler-Free Mode: [f 2 4 0][e]
[s]Done[e]

[msg SPOILER_TOGGLE[Find A Friend (Dexxtrip)]]
[s]If "On", only Social Links you have discovered
[n]and initiated Rank 1 with will be shown.[e]

[msg ShowClockOptions_Text]
[s]Show Clock Option[e]

[sel ShowClockOptions]
[s]Use Traesto Gem: [f 2 4 0][e]
[s]Done[e]

[msg ShowClock_Traesto[Clock Traesto (moddaman)]]
[s]A tweak designed to improve balance. If "On", 
[n]calling the Clock will additionally require a 
[n][f 2 4 2] or having Escape Route unlocked.[e]

