[sel DORMITORY_SHOTCUTSEL top]
[s]1F, Lounge[e]
[s]2F, Hallway[e]
[s]3F, Hallway[e]
[s]4F, Hallway[e]
[s]Command Room[e]
[s]Your Room[e]
[s]Bed[e]
[s]Town Map[e]
[s]Quick Travel[e]
[s]View calendar[e]
[s]Spend time with...[e]
[s]Save[e]
[s]Mod Menu[e]

[msg GO_OUT_OK_HELP]
[s]If you go outside, when you come
[n]back to the dorm, it will become
[n]nighttime.
[n][w][e]
[s](This can be changed by enabling
[n]Go Back Home Easily from the
[n]Custom Sub Menu configuration.)
[n][w][e]